language: java
jdk:
 - openjdk11

install:
- mvn clean install -P bootstrap
- mvn install

notifications:
 email:
   recipients:
    - travis-ci.mellifluent@hohenegger.eu
   on_success: change
   on_failure: always
